export const allproducts = [
  {
    photo_product: "/images/products/revlon.png",
    brand: "Revlon",
    name_product: "Base de maquillaje pieles normales/secas",
    price: "$14.50",
  },
  {
    photo_product: "/images/products/annoa.png",
    brand: "Annoa",
    name_product: "Base de maquillaje alta cobertura",
    price: "$18.90",
  },
  {
    photo_product: "/images/products/beauty.png",
    brand: "BeautyCreations",
    name_product: "Corrector líquido alta cobertura",
    price: "$6.30",
  },
  {
    photo_product: "/images/products/kleancolor.png",
    brand: "KleanColor",
    name_product: "Paleta de iluminadores",
    price: "$7.00",
  },
  {
    photo_product: "/images/products/lbel.png",
    brand: "L’BEL",
    name_product: "Polvo suelto extrafinos",
    price: "$17.62",
  },
  {
    photo_product: "/images/products/jacqueline.png",
    brand: "Jacqueline",
    name_product: "Set de brochas 12 pza",
    price: "$25.00",
  },
  {
    photo_product: "/images/products/maybelline.png",
    brand: "Maybelline",
    name_product: "Lip Gloss",
    price: "$10.00",
  },
  {
    photo_product: "/images/products/handayah.png",
    brand: "Handayah",
    name_product: "Delineador a prueba de agua",
    price: "$6.90",
  },
  {
    photo_product: "/images/products/vogue.png",
    brand: "Vogue",
    name_product: "Máscara de pestañas a prueba de agua",
    price: "$8.55",
  },
  {
    photo_product: "/images/products/sheglam.png",
    brand: "Sheglam",
    name_product: "Rubor líquido",
    price: "$11.30",
  },
  {
    photo_product: "/images/products/byphasse.png",
    brand: "Byphasse",
    name_product: "Fijador de maquillaje",
    price: "$7.00",
  },
  {
    photo_product: "/images/products/covergirl.png",
    brand: "Covergirl",
    name_product: "Labial líquido mate",
    price: "$11.91",
  },
  {
    photo_product: "/images/products2/foreo.png",
    brand: "FOREO",
    name_product: "Luna Foreo MINI",
    price: "$55.00",
  },
  {
    photo_product: "/images/products2/leicare.png",
    brand: "Leicare",
    name_product: "Rodillo facial de Jade y Gua Sha",
    price: "$14.99",
  },
  {
    photo_product: "/images/products2/hailicare.png",
    brand: "Hailicare",
    name_product: "Depurador de piel ultrasónico",
    price: "$60.00",
  },
  {
    photo_product: "/images/products2/florence.png",
    brand: "Florence",
    name_product: "Parches de colágeno para ojeras y arrugas",
    price: "$24.99",
  },
  {
    photo_product: "/images/products2/ncana.png",
    brand: "Ncana",
    name_product: "Set de extractor de comedones",
    price: "$9.99",
  },
  {
    photo_product: "/images/products2/gloria.png",
    brand: "GloriaSaltos",
    name_product: "Navajas depiladoras de cejas",
    price: "$4.99",
  },
  {
    photo_product: "/images/products2/rotek.png",
    brand: "Rotekt1740",
    name_product: "Masajeador facial con rodillo",
    price: "$5.00",
  },
  //   {
  //     photo_product: "/images/products2/fraicheur.png",
  //     brand: "Fraicheur",
  //     name_product: "Esferas de vidrio masajeadoras",
  //     price: "$18.35",
  //   },
  {
    photo_product: "/images/products2/rotek2.png",
    brand: "Rotekt1740",
    name_product: "Extractor de puntos negros",
    price: "$44.99",
  },
  {
    photo_product: "/images/products3/nyo.png",
    brand: "ma:nyo",
    name_product: "Aceite facial limpiador",
    price: "$28.99",
  },
  {
    photo_product: "/images/products3/cerave.png",
    brand: "CeraVe",
    name_product: "Espuma facial limpiadora para pieles grasas",
    price: "$17.99",
  },
  {
    photo_product: "/images/products3/anua.png",
    brand: "Anua",
    name_product: "Tonificador para piel ultra sensible",
    price: "$19.90",
  },
  {
    photo_product: "/images/products3/tocobo.png",
    brand: "Tocobo",
    name_product: "Protector solar con ácido hialuronico",
    price: "$26.90",
  },
  {
    photo_product: "/images/products3/teami.png",
    brand: "teamí",
    name_product: "Mascarilla restauradora",
    price: "$36.00",
  },
  {
    photo_product: "/images/products3/theordinary.png",
    brand: "The Ordinary",
    name_product: "Hidratante con niacinamida",
    price: "$17.99",
  },
  {
    photo_product: "/images/products3/lancome.png",
    brand: "Lancôme",
    name_product: "Exfoliante con agua de rosas",
    price: "$32.00",
  },
  {
    photo_product: "/images/products3/paula.png",
    brand: "Paula’s Choice",
    name_product: "Serum anti manchas ",
    price: "$60.00",
  },
];
